on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:NoPallets/client.git"
          source_branch: "master"
          destination_repo: "git@github.com:StanislavSt/nopallets-deployment.git"
          destination_branch: "master"
          source_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
