# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://NoPallets:${{ secrets.SYNC_ACCESS_TOKEN }}@github.com/NoPallets/client.git"
          source_branch: "master"
          destination_repo: "StanislavSt/NoPallets-client"
          destination_branch: "master"
